version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 438465160558.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t laravel .
      - docker tag laravel:latest 438465160558.dkr.ecr.us-east-1.amazonaws.com/laravel:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 438465160558.dkr.ecr.us-east-1.amazonaws.com/laravel:latest
      - echo Writing imagedefinitions.json file...
      - printf '[{"name":"laravel","imageUri":"%s"}]' "438465160558.dkr.ecr.us-east-1.amazonaws.com/laravel:latest" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
